export const ACTION_TYPE = {
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    PERCANTAGE_TIME_PASSED: 'PERCENTAGE_TIME_PASSED',
    GET_TICKETS_LOADING: "TICKETS_LOADING",
    GET_TICKETS_TX_ID: "GET_TICKETS_TX_ID",
    MODAL_OPEN: 'MODAL_OPEN',
    MODAL_TYPE: "MODAL_TYPE"
}